### PR TITLE
fix G gain matrix multiplication when n>m

### LINKED ISSUE #16: When H is non square I get "ValueError: operands could not be broadcast..."
On the python version I get this error `ValueError: operands could not be broadcast together with shapes` when I have a H matrix which is not square, in particular when I have more states than sensors so when n>m.

The error is raised by this line 
https://github.com/simondlevy/TinyEKF/blob/master/extras/python/tinyekf/__init__.py#L59

Probably it's the same problem reported in #5

### PR DESCRIPTION
**Pull request by guglie**
This fixes #16 and probably #5 using numpy.dot function instead of * operand for matrix multiplication

### CODE REVIEW

**Comment by simondlevy** [comment]
Thanks, guglie!

**Comment by RichardSWheatley** [comment]
@guglie Is it possible that this line in this same file also needs to change to using the dot product?

self.P_pre = F * self.P_post * F.T + self.Q

**Comment by guglie** [comment]
@simondlevy no problem, thank you for the EKF tutorial!
I was wondering why my filter wasn't working and found the fix 😃 

@wher0001 It is possible, if you agree @simondlevy I can make a pull using the dot function in all the multiplications. Where is already used the `np.dot(A,B)` function I suggest to use the method version `A.dot(B)` which to me is more readable.

**Comment by RichardSWheatley** [comment]
There should be a way to test if it is needed I'm certain spots.

I wish I had the time to look at it.

Good find btw!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request merged**
